# Generated by Django 4.1.7 on 2023-03-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SketchBinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('binary_file', models.FileField(upload_to='robot_binaries')),
                ('description', models.TextField()),
                ('last_run_datetime', models.DateTimeField()),
            ],
        ),
    ]
