# Generated by Django 4.1.7 on 2023-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchbinary',
            name='last_run_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
