# Generated by Django 4.1.7 on 2023-03-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot', '0002_alter_sketchbinary_last_run_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketchbinary',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
