# Generated by Django 4.1.7 on 2023-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_sketchbinary_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchbinary',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
